# Generated by Django 4.1.3 on 2022-12-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
