# Generated by Django 3.2.5 on 2023-01-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_api', '0002_alter_employee_empname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateField(),
        ),
    ]
